#!/usr/bin/env node
/**
 * Seed script — inserts 40 realistic UK property listings into the meridian database.
 *
 * Usage:
 *   cd server
 *   node src/scripts/seedProperties.js
 *
 * Behaviour:
 *   - Connects to MONGODB_URI from .env
 *   - Creates a default agent user if none exists (email: agent@meridian.co.uk)
 *   - Clears existing Property documents, then inserts all 40 mock properties
 *   - Safe to re-run — always starts from a clean slate
 */
import 'dotenv/config';
import mongoose from 'mongoose';
import User from '../models/User.js';
import Property from '../models/Property.js';

// ── Cloudinary sample image sets ──────────────────────────────────────────
const IMG = {
  houseExterior: [
    { url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800', caption: 'Front elevation',    roomType: 'exterior' },
    { url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800', caption: 'Side garden view',   roomType: 'exterior' },
    { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6d349a58?w=800', caption: 'Open-plan kitchen',  roomType: 'kitchen'  },
    { url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800', caption: 'Master bedroom',      roomType: 'bedroom'  },
    { url: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800', caption: 'Family bathroom',    roomType: 'bathroom' },
  ],
  modernFlat: [
    { url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800', caption: 'Living area',        roomType: 'living room' },
    { url: 'https://images.unsplash.com/photo-1574739782594-db4ead022697?w=800', caption: 'Kitchen diner',      roomType: 'kitchen'     },
    { url: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800', caption: 'Double bedroom',     roomType: 'bedroom'     },
    { url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800', caption: 'Shower room',         roomType: 'bathroom'    },
  ],
  luxuryHouse: [
    { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800', caption: 'Grand entrance',     roomType: 'exterior'    },
    { url: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800', caption: 'Reception hall',     roomType: 'living room' },
    { url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800', caption: 'Chef\'s kitchen',     roomType: 'kitchen'     },
    { url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800', caption: 'Principal suite',    roomType: 'bedroom'     },
    { url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800', caption: 'En-suite bathroom',   roomType: 'bathroom'    },
    { url: 'https://images.unsplash.com/photo-1600566752547-5c3b3e3e3e3e?w=800', caption: 'Private garden',    roomType: 'exterior'    },
  ],
  studio: [
    { url: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800', caption: 'Studio space',       roomType: 'living room' },
    { url: 'https://images.unsplash.com/photo-1574739782594-db4ead022697?w=800', caption: 'Kitchenette',        roomType: 'kitchen'     },
    { url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800', caption: 'Bathroom',             roomType: 'bathroom'    },
  ],
  commercial: [
    { url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800', caption: 'Open office floor',  roomType: 'office'    },
    { url: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800', caption: 'Meeting room',       roomType: 'office'    },
    { url: 'https://images.unsplash.com/photo-1497366754035-f200586c4a78?w=800', caption: 'Reception area',     roomType: 'reception' },
  ],
};

// ── Sample AI valuation objects ───────────────────────────────────────────
const VALUATIONS = [
  { verdict: 'Fairly Priced', confidence: 84, pricePerSqFt: 612, rentalYield: '4.1%', marketTrend: 'Stable demand in this postcode district.', recommendation: 'Reasonable entry point for owner-occupiers and investors alike.' },
  { verdict: 'Great Deal',    confidence: 91, pricePerSqFt: 540, rentalYield: '5.2%', marketTrend: 'Rising demand driven by transport upgrades.',  recommendation: 'Act quickly — comparable properties are selling above asking price.' },
  { verdict: 'Overpriced',    confidence: 76, pricePerSqFt: 780, rentalYield: '3.2%', marketTrend: 'Market softening slightly in this area.',        recommendation: 'Negotiate 5–8% below asking before proceeding.' },
  { verdict: 'Fairly Priced', confidence: 88, pricePerSqFt: 495, rentalYield: '4.8%', marketTrend: 'Consistent rental demand from young professionals.', recommendation: 'Strong buy-to-let candidate with good yield prospects.' },
];

// ── Mock property data ────────────────────────────────────────────────────
// `agent` is populated at runtime with the seeded agent's _id.
export const mockProperties = (agentId) => [

  // ── LONDON ────────────────────────────────────────────────────────────────
  {
    title:       '4-Bed Victorian Terraced House — Islington',
    description: 'A beautifully restored Victorian terrace retaining many period features including original cornicing, sash windows, and cast-iron fireplaces. The generous rear garden is south-facing. Walking distance to Angel tube.',
    price:       1_450_000,
    bedrooms:    4,
    bathrooms:   2,
    propertyType:'house',
    location:    { address: '14 Barnsbury Street', city: 'London', postcode: 'N1 1PN', lat: 51.5381, lng: -0.1090 },
    images:      IMG.houseExterior,
    agent:       agentId,
    status:      'active',
    aiDescription: 'Step into a piece of London history with this magnificently restored Victorian terrace in the heart of Islington. Original features blend seamlessly with contemporary finishes throughout four spacious bedrooms, while the south-facing garden provides a rare urban oasis. Moments from the vibrant Upper Street and Angel Underground, this is an exceptional family home.',
    aiValuation: VALUATIONS[0],
  },
  {
    title:       '2-Bed Luxury Apartment — Canary Wharf',
    description: 'High-specification apartment on the 18th floor of a landmark riverside development. Floor-to-ceiling windows frame sweeping Thames views. Concierge, gym, and residents\' roof terrace included.',
    price:       875_000,
    bedrooms:    2,
    bathrooms:   2,
    propertyType:'flat',
    location:    { address: 'Apt 18C, South Quay Plaza', city: 'London', postcode: 'E14 9SH', lat: 51.5003, lng: -0.0200 },
    images:      IMG.modernFlat,
    agent:       agentId,
    status:      'active',
    aiDescription: 'Commanding views of the Thames from the 18th floor define this exceptional apartment in South Quay Plaza. Finished to the highest specification, the open-plan living space flows effortlessly onto a private balcony. Two generous double bedrooms, two bathrooms, and access to world-class amenities make this a benchmark for London living.',
    aiValuation: VALUATIONS[1],
  },
  {
    title:       '5-Bed Detached House — Hampstead',
    description: 'An imposing Edwardian detached home set behind a walled garden on one of Hampstead\'s most sought-after roads. Principal bedroom with dressing room and en-suite. Double garage and off-street parking.',
    price:       3_200_000,
    bedrooms:    5,
    bathrooms:   4,
    propertyType:'house',
    location:    { address: '7 Frognal Rise', city: 'London', postcode: 'NW3 6EG', lat: 51.5579, lng: -0.1811 },
    images:      IMG.luxuryHouse,
    agent:       agentId,
    status:      'active',
    aiDescription: 'A rare opportunity to acquire a substantial Edwardian family home in prestigious Frognal Rise. Set behind private gates with a walled garden, this magnificent property offers five reception rooms, five bedrooms with luxurious en-suite facilities, and a recently extended kitchen-diner. The Heath is mere minutes away.',
    aiValuation: VALUATIONS[2],
  },
  {
    title:       'Studio Apartment — Shoreditch',
    description: 'Smart studio in the heart of creative Shoreditch. Exposed brick walls, polished concrete floors, and a bespoke fitted kitchen. Ideal for young professionals. Excellent transport links.',
    price:       365_000,
    bedrooms:    0,
    bathrooms:   1,
    propertyType:'studio',
    location:    { address: '3A Curtain Road', city: 'London', postcode: 'EC2A 3LT', lat: 51.5244, lng: -0.0803 },
    images:      IMG.studio,
    agent:       agentId,
    status:      'active',
    aiDescription: 'Urban living at its finest in the heart of Shoreditch. This intelligently designed studio apartment features exposed brick walls and polished concrete floors that celebrate the building\'s industrial heritage. The bespoke kitchen and contemporary bathroom complete an ideal pied-à-terre for the discerning city professional.',
    aiValuation: VALUATIONS[3],
  },
  {
    title:       '3-Bed Semi-Detached — Dulwich Village',
    description: 'Charming 1930s semi-detached in the heart of Dulwich Village. Original parquet flooring, bay windows to front and rear. Well-established garden with mature trees. Catchment for outstanding schools.',
    price:       985_000,
    bedrooms:    3,
    bathrooms:   2,
    propertyType:'house',
    location:    { address: '22 Calton Avenue', city: 'London', postcode: 'SE21 7DG', lat: 51.4467, lng: -0.0832 },
    images:      IMG.houseExterior,
    agent:       agentId,
    status:      'active',
    aiDescription: 'Nestled in the leafy tranquillity of Dulwich Village, this elegantly proportioned 1930s semi-detached home retains all of its original charm. Original parquet flooring, generous bay windows, and a beautifully mature garden create an idyllic family environment, while outstanding schools and the village high street are just a short stroll away.',
    aiValuation: VALUATIONS[0],
  },
  {
    title:       '1-Bed Flat — Notting Hill',
    description: 'Bright and airy first-floor flat in a sought-after garden square conversion. High ceilings, cornicing, and a private patio garden. Share of freehold. Portobello Road on your doorstep.',
    price:       675_000,
    bedrooms:    1,
    bathrooms:   1,
    propertyType:'flat',
    location:    { address: '9 Pembridge Villas', city: 'London', postcode: 'W11 3EP', lat: 51.5110, lng: -0.1977 },
    images:      IMG.modernFlat,
    agent:       agentId,
    status:      'active',
    aiDescription: 'Occupying the first floor of a gracious garden-square conversion, this beautifully presented apartment combines period elegance with modern convenience. Soaring ceilings, intricate cornicing, and a rare private patio garden set it apart, while share of freehold provides exceptional security of tenure in one of West London\'s most desirable postcodes.',
    aiValuation: VALUATIONS[1],
  },
  {
    title:       'Office Space 2,200 sqft — Clerkenwell',
    description: 'Spectacular self-contained office unit in a converted Victorian ink factory. Exposed steelwork, full-height windows, and a private roof terrace. Cat 6 wiring throughout. Ideal for a tech or creative studio.',
    price:       1_100_000,
    bedrooms:    0,
    bathrooms:   2,
    propertyType:'commercial',
    location:    { address: '45 St John Street', city: 'London', postcode: 'EC1V 4JL', lat: 51.5238, lng: -0.1035 },
    images:      IMG.commercial,
    agent:       agentId,
    status:      'active',
    aiDescription: 'A unique opportunity to acquire a self-contained commercial unit within one of Clerkenwell\'s most characterful conversions. The former Victorian ink factory retains its striking exposed steelwork and full-height windows, creating an inspiring workspace across 2,200 sq ft with the bonus of a private roof terrace overlooking the City skyline.',
    aiValuation: {},
  },
  {
    title:       '2-Bed Ground Floor Flat — Clapham',
    description: 'Spacious ground-floor garden flat in a period conversion. Two double bedrooms, a large eat-in kitchen, and direct access to a 40ft south-facing garden. Off-street parking space included.',
    price:       745_000,
    bedrooms:    2,
    bathrooms:   1,
    propertyType:'flat',
    location:    { address: '6 Abbeville Road', city: 'London', postcode: 'SW4 9NG', lat: 51.4545, lng: -0.1456 },
    images:      IMG.modernFlat,
    agent:       agentId,
    status:      'sold',
    aiDescription: '',
    aiValuation: {},
  },
  {
    title:       '3-Bed Townhouse — Greenwich',
    description: 'Contemporary three-storey townhouse in a quiet mews development near Greenwich Park. Integrated appliances, underfloor heating throughout, private courtyard garden, and residents\' parking.',
    price:       795_000,
    bedrooms:    3,
    bathrooms:   3,
    propertyType:'house',
    location:    { address: '2 Park Vista Mews', city: 'London', postcode: 'SE10 9NW', lat: 51.4779, lng: -0.0015 },
    images:      IMG.houseExterior,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: VALUATIONS[3],
  },
  {
    title:       'Studio — Bethnal Green',
    description: 'Compact and cleverly designed studio in a new-build development moments from Bethnal Green tube. Juliet balcony, integrated appliances, and 24-hour concierge. Ideal first-time buy or investment.',
    price:       320_000,
    bedrooms:    0,
    bathrooms:   1,
    propertyType:'studio',
    location:    { address: 'Apt 4, Roman Road Quarter', city: 'London', postcode: 'E2 0HU', lat: 51.5268, lng: -0.0558 },
    images:      IMG.studio,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: {},
  },

  // ── MANCHESTER ────────────────────────────────────────────────────────────
  {
    title:       '4-Bed Detached House — Didsbury',
    description: 'Impressive detached family home in the popular Didsbury village area. Landscaped gardens front and rear, a double garage, and a recently extended kitchen-family room spanning the full width of the property.',
    price:       685_000,
    bedrooms:    4,
    bathrooms:   3,
    propertyType:'house',
    location:    { address: '31 Lapwing Lane', city: 'Manchester', postcode: 'M20 2NT', lat: 53.4094, lng: -2.2283 },
    images:      IMG.houseExterior,
    agent:       agentId,
    status:      'active',
    aiDescription: 'Set in one of South Manchester\'s most coveted village settings, this striking detached home delivers space and style in equal measure. The recently extended kitchen-family room creates an outstanding sociable heart to the home, while four generous bedrooms and three bathrooms cater comfortably for a growing family.',
    aiValuation: VALUATIONS[1],
  },
  {
    title:       '2-Bed Apartment — Spinningfields',
    description: 'Chic city-centre apartment in the prestigious Spinningfields development. Secure underground parking, concierge, residents\' gym, and a terrace with views over the financial district.',
    price:       385_000,
    bedrooms:    2,
    bathrooms:   2,
    propertyType:'flat',
    location:    { address: 'Apt 12, 1 Hardman Square', city: 'Manchester', postcode: 'M3 3EB', lat: 53.4805, lng: -2.2498 },
    images:      IMG.modernFlat,
    agent:       agentId,
    status:      'active',
    aiDescription: 'Positioned in the heart of Manchester\'s prestigious Spinningfields quarter, this sophisticated two-bedroom apartment is finished to an exceptional standard. Floor-to-ceiling glazing floods the open-plan living space with natural light, while secure underground parking and a residents\' concierge complete the premium lifestyle offering.',
    aiValuation: VALUATIONS[0],
  },
  {
    title:       '3-Bed Semi-Detached — Chorlton',
    description: 'Lovingly maintained Edwardian semi in the heart of Chorlton. Open-plan living and dining room, recently renovated kitchen, and a 100ft rear garden with a summer house. Close to Chorlton-cum-Hardy tram stop.',
    price:       475_000,
    bedrooms:    3,
    bathrooms:   1,
    propertyType:'house',
    location:    { address: '78 Nicolas Road', city: 'Manchester', postcode: 'M21 9LG', lat: 53.4395, lng: -2.2677 },
    images:      IMG.houseExterior,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: {},
  },
  {
    title:       'Studio — Northern Quarter',
    description: 'Stylish converted studio in the iconic NOMA development. Exposed brickwork, bespoke fitted furniture, and a walk-in shower. The building features a residents\' rooftop bar. Perfect for young professionals.',
    price:       185_000,
    bedrooms:    0,
    bathrooms:   1,
    propertyType:'studio',
    location:    { address: 'Apt 7, NOMA, 7 Angel Square', city: 'Manchester', postcode: 'M60 0AG', lat: 53.4863, lng: -2.2390 },
    images:      IMG.studio,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: {},
  },
  {
    title:       'Commercial Unit 1,800 sqft — Ancoats',
    description: 'Ground-floor retail or restaurant unit in the award-winning Ancoats regeneration quarter. Full shop-front glazing, high ceilings, and excellent footfall. Available with new 10-year FRI lease.',
    price:       420_000,
    bedrooms:    0,
    bathrooms:   1,
    propertyType:'commercial',
    location:    { address: '18 Blossom Street', city: 'Manchester', postcode: 'M4 6AJ', lat: 53.4854, lng: -2.2227 },
    images:      IMG.commercial,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: {},
  },

  // ── BRISTOL ───────────────────────────────────────────────────────────────
  {
    title:       '5-Bed Georgian Townhouse — Clifton',
    description: 'A stunning Grade II listed Georgian townhouse arranged over five floors in the heart of Clifton Village. Original shutters and fireplaces throughout, a west-facing walled garden, and a detached coach house.',
    price:       1_850_000,
    bedrooms:    5,
    bathrooms:   3,
    propertyType:'house',
    location:    { address: '4 Royal York Crescent', city: 'Bristol', postcode: 'BS8 4JY', lat: 51.4606, lng: -2.6213 },
    images:      IMG.luxuryHouse,
    agent:       agentId,
    status:      'active',
    aiDescription: 'A magnificent Grade II listed townhouse on Bristol\'s celebrated Royal York Crescent, offering five floors of exquisitely proportioned accommodation. Original Georgian features — shuttered sash windows, marble fireplaces, and intricate plasterwork — are complemented by a carefully designed contemporary interior. The west-facing walled garden and detached coach house complete an exceptional offering.',
    aiValuation: VALUATIONS[0],
  },
  {
    title:       '2-Bed Flat — Harbourside',
    description: 'Contemporary apartment with direct Floating Harbour views. Wide balcony, open-plan kitchen-living room, two double bedrooms, and a private parking space. Walking distance to Bristol\'s vibrant waterfront restaurants.',
    price:       425_000,
    bedrooms:    2,
    bathrooms:   2,
    propertyType:'flat',
    location:    { address: 'Apt 9, Harbour Court, Rope Walk', city: 'Bristol', postcode: 'BS1 5DB', lat: 51.4492, lng: -2.5998 },
    images:      IMG.modernFlat,
    agent:       agentId,
    status:      'active',
    aiDescription: 'Wake up to sweeping views of Bristol\'s famous Floating Harbour from this beautifully appointed waterfront apartment. The wide south-facing balcony, sleek open-plan kitchen, and two generously proportioned bedrooms make this an outstanding city-centre home, while the vibrant waterfront restaurants and bars are just steps away.',
    aiValuation: VALUATIONS[1],
  },
  {
    title:       '4-Bed Detached — Stoke Bishop',
    description: 'Substantial modern detached family home in a quiet cul-de-sac in desirable Stoke Bishop. Four reception rooms, a principal suite with dressing room, a heated outdoor pool, and an integral double garage.',
    price:       1_100_000,
    bedrooms:    4,
    bathrooms:   3,
    propertyType:'house',
    location:    { address: '5 Sea Mills Lane', city: 'Bristol', postcode: 'BS9 2HX', lat: 51.4821, lng: -2.6356 },
    images:      IMG.houseExterior,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: VALUATIONS[2],
  },
  {
    title:       '1-Bed Flat — Stokes Croft',
    description: 'Characterful first-floor flat in a converted Victorian warehouse. Exposed ceiling beams, original ironwork windows, a mezzanine study area, and a private roof terrace. Heart of Bristol\'s creative quarter.',
    price:       275_000,
    bedrooms:    1,
    bathrooms:   1,
    propertyType:'flat',
    location:    { address: '34 Jamaica Street', city: 'Bristol', postcode: 'BS2 8JQ', lat: 51.4637, lng: -2.5917 },
    images:      IMG.modernFlat,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: {},
  },
  {
    title:       '3-Bed Terraced House — Montpelier',
    description: 'Vibrant Victorian terraced house in Bristol\'s bohemian Montpelier neighbourhood. Extended rear kitchen-diner, two receptions, a paved courtyard garden, and a study. Two minutes from Picton Street\'s independent shops.',
    price:       560_000,
    bedrooms:    3,
    bathrooms:   2,
    propertyType:'house',
    location:    { address: '11 Hampton Road', city: 'Bristol', postcode: 'BS6 6HT', lat: 51.4700, lng: -2.5827 },
    images:      IMG.houseExterior,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: {},
  },

  // ── LEEDS ─────────────────────────────────────────────────────────────────
  {
    title:       '4-Bed Detached — Roundhay',
    description: 'Substantial red-brick detached home backing onto Roundhay Park. Recently extended to create a large open-plan kitchen-family room. Principal suite with a walk-in wardrobe and en-suite bathroom.',
    price:       595_000,
    bedrooms:    4,
    bathrooms:   3,
    propertyType:'house',
    location:    { address: '19 Prince\'s Avenue', city: 'Leeds', postcode: 'LS8 2EX', lat: 53.8328, lng: -1.5172 },
    images:      IMG.houseExterior,
    agent:       agentId,
    status:      'active',
    aiDescription: 'Backing directly onto the magnificent Roundhay Park, this substantial red-brick family home combines generous proportions with a beautifully contemporary interior. The recently extended kitchen-family room is the undisputed heart of the home, perfect for modern family life, while four bedrooms and three bathrooms serve with equal distinction.',
    aiValuation: VALUATIONS[3],
  },
  {
    title:       '2-Bed Apartment — Leeds Dock',
    description: 'Modern waterside apartment in the award-winning Leeds Dock development. Open-plan living with a Juliet balcony overlooking the canal, two double bedrooms, and a secure parking space.',
    price:       265_000,
    bedrooms:    2,
    bathrooms:   2,
    propertyType:'flat',
    location:    { address: 'Apt 24, Brewers Wharf, Dock Street', city: 'Leeds', postcode: 'LS10 1JF', lat: 53.7952, lng: -1.5379 },
    images:      IMG.modernFlat,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: VALUATIONS[0],
  },
  {
    title:       '3-Bed Semi-Detached — Chapel Allerton',
    description: 'Bright Edwardian semi in popular Chapel Allerton. Open plan ground floor, generous rear garden with a decked terrace. Close to the vibrant Harrogate Road cafés and excellent primary schools.',
    price:       380_000,
    bedrooms:    3,
    bathrooms:   1,
    propertyType:'house',
    location:    { address: '54 Stainbeck Road', city: 'Leeds', postcode: 'LS7 3QY', lat: 53.8308, lng: -1.5424 },
    images:      IMG.houseExterior,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: {},
  },
  {
    title:       'Studio — Leeds City Centre',
    description: 'Smart purpose-built studio in the heart of Leeds city centre. Modern fitted kitchen, walk-in shower, and allocated parking space. Excellent rental investment with strong student and professional demand.',
    price:       130_000,
    bedrooms:    0,
    bathrooms:   1,
    propertyType:'studio',
    location:    { address: 'Apt 3, Civic Quarter, Great George Street', city: 'Leeds', postcode: 'LS1 3DL', lat: 53.7997, lng: -1.5492 },
    images:      IMG.studio,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: {},
  },

  // ── EDINBURGH ─────────────────────────────────────────────────────────────
  {
    title:       '3-Bed Georgian Flat — New Town',
    description: 'A magnificent upper-floor Georgian apartment in Edinburgh\'s World Heritage New Town. Original cornicing, shuttered windows, and marble fireplaces throughout. Communal garden access. Share of freehold.',
    price:       895_000,
    bedrooms:    3,
    bathrooms:   2,
    propertyType:'flat',
    location:    { address: '22 Heriot Row', city: 'Edinburgh', postcode: 'EH3 6ES', lat: 55.9541, lng: -3.2016 },
    images:      IMG.modernFlat,
    agent:       agentId,
    status:      'active',
    aiDescription: 'Occupying the upper floors of a World Heritage listed townhouse on one of Edinburgh\'s finest streets, this extraordinary Georgian apartment is a rare trophy acquisition. Three principal bedrooms, two reception rooms, and a wealth of period features combine effortlessly with a modern kitchen and bathrooms to create an outstanding New Town home.',
    aiValuation: VALUATIONS[0],
  },
  {
    title:       '5-Bed Detached Villa — Morningside',
    description: 'An exceptional stone-built Victorian villa in the heart of Morningside. Five bedrooms, a drawing room with bay window, a detached studio office, and walled gardens extending to 0.25 acres.',
    price:       1_650_000,
    bedrooms:    5,
    bathrooms:   4,
    propertyType:'house',
    location:    { address: '3 Midmar Gardens', city: 'Edinburgh', postcode: 'EH10 6DY', lat: 55.9292, lng: -3.2113 },
    images:      IMG.luxuryHouse,
    agent:       agentId,
    status:      'active',
    aiDescription: 'A landmark Victorian villa of considerable distinction, set within walled gardens of approximately a quarter of an acre in the heart of Edinburgh\'s most sought-after suburb. Five bedrooms, five reception rooms, and a detached studio office deliver flexibility rarely found even at this price point. An outstanding family home offered for the first time in 22 years.',
    aiValuation: VALUATIONS[1],
  },
  {
    title:       '2-Bed Tenement Flat — Stockbridge',
    description: 'A well-maintained traditional tenement flat in bohemian Stockbridge. Two double bedrooms, a generous reception room, a fitted kitchen with dining area, and a private storage unit.',
    price:       385_000,
    bedrooms:    2,
    bathrooms:   1,
    propertyType:'flat',
    location:    { address: '41 St Stephen Street', city: 'Edinburgh', postcode: 'EH3 5AB', lat: 55.9571, lng: -3.2079 },
    images:      IMG.modernFlat,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: {},
  },
  {
    title:       'Office Suite 1,500 sqft — Leith',
    description: 'Flexible office suite within a prestigious converted bonded warehouse in the creative Leith docks quarter. Exposed stone walls, timber beams, and a private car park for six vehicles.',
    price:       550_000,
    bedrooms:    0,
    bathrooms:   2,
    propertyType:'commercial',
    location:    { address: '8 The Shore', city: 'Edinburgh', postcode: 'EH6 6QW', lat: 55.9756, lng: -3.1720 },
    images:      IMG.commercial,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: {},
  },

  // ── BIRMINGHAM ────────────────────────────────────────────────────────────
  {
    title:       '3-Bed Semi-Detached — Moseley',
    description: 'Classic 1930s semi-detached in sought-after Moseley. Bay windows, a traditional tiled hallway, generous rear garden, and a large loft room with potential to convert. Excellent schools nearby.',
    price:       395_000,
    bedrooms:    3,
    bathrooms:   1,
    propertyType:'house',
    location:    { address: '66 Oxford Road', city: 'Birmingham', postcode: 'B13 9ES', lat: 52.4414, lng: -1.8898 },
    images:      IMG.houseExterior,
    agent:       agentId,
    status:      'active',
    aiDescription: 'Presented in immaculate condition, this quintessential 1930s semi-detached home in popular Moseley retains all of its original charm. Bay windows and tiled hallway greet you on arrival, while the generous rear garden and unconverted loft room offer exciting scope for further enhancement.',
    aiValuation: VALUATIONS[3],
  },
  {
    title:       '2-Bed Apartment — Brindleyplace',
    description: 'Contemporary apartment in the landmark Brindleyplace waterside development. Balcony overlooking the canal basin, open-plan living, underground parking, and concierge. Close to Broad Street entertainment.',
    price:       299_000,
    bedrooms:    2,
    bathrooms:   2,
    propertyType:'flat',
    location:    { address: 'Apt 11, 1 Brunswick Square', city: 'Birmingham', postcode: 'B1 2LP', lat: 52.4783, lng: -1.9148 },
    images:      IMG.modernFlat,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: VALUATIONS[0],
  },
  {
    title:       '4-Bed Detached — Sutton Coldfield',
    description: 'Executive detached home in a prestigious Sutton Coldfield address. Landscaped gardens, a cinema room, a principal bedroom suite with a walk-in wardrobe, and a triple garage. Gated development.',
    price:       875_000,
    bedrooms:    4,
    bathrooms:   4,
    propertyType:'house',
    location:    { address: '2 Four Oaks Road', city: 'Birmingham', postcode: 'B74 2TW', lat: 52.5763, lng: -1.8316 },
    images:      IMG.luxuryHouse,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: {},
  },
  {
    title:       'Studio Apartment — Jewellery Quarter',
    description: 'Chic studio in a converted Victorian factory in Birmingham\'s iconic Jewellery Quarter. Polished concrete floors, Crittall-style windows, a compact fitted kitchen, and a walk-in shower.',
    price:       159_000,
    bedrooms:    0,
    bathrooms:   1,
    propertyType:'studio',
    location:    { address: 'Unit 5, Vyse Street Works', city: 'Birmingham', postcode: 'B18 6LP', lat: 52.4878, lng: -1.9098 },
    images:      IMG.studio,
    agent:       agentId,
    status:      'archived',
    aiDescription: '',
    aiValuation: {},
  },

  // ── BATH ──────────────────────────────────────────────────────────────────
  {
    title:       '4-Bed Georgian Townhouse — City Centre',
    description: 'A breathtaking Grade I listed Georgian townhouse in the heart of Bath\'s World Heritage city centre. Five principal rooms across four floors, a stone vaulted cellar, and a south-facing walled courtyard garden.',
    price:       2_250_000,
    bedrooms:    4,
    bathrooms:   3,
    propertyType:'house',
    location:    { address: '11 The Circus', city: 'Bath', postcode: 'BA1 2EW', lat: 51.3837, lng: -2.3673 },
    images:      IMG.luxuryHouse,
    agent:       agentId,
    status:      'active',
    aiDescription: 'An extraordinary opportunity to acquire a Grade I listed townhouse on Bath\'s world-famous Circus, one of the finest examples of Georgian architecture in existence. Retaining original fireplaces, plasterwork, and stone-flagged floors, this remarkable home is a once-in-a-generation purchase in one of England\'s most celebrated addresses.',
    aiValuation: VALUATIONS[0],
  },
  {
    title:       '2-Bed Garden Flat — Bathwick',
    description: 'A delightful lower-ground-floor garden flat in the Bathwick conservation area. Two double bedrooms, a sitting room with original period fireplace, a modern kitchen, and exclusive use of a walled garden.',
    price:       465_000,
    bedrooms:    2,
    bathrooms:   1,
    propertyType:'flat',
    location:    { address: '8 Bathwick Hill', city: 'Bath', postcode: 'BA2 6EH', lat: 51.3821, lng: -2.3534 },
    images:      IMG.modernFlat,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: VALUATIONS[1],
  },
  {
    title:       '3-Bed Victorian Terraced — Larkhall',
    description: 'Immaculately presented Victorian terrace in Bath\'s fashionable Larkhall neighbourhood. Open-plan kitchen-diner, a south-facing tiered garden, a loft bedroom with roof lights, and a home office.',
    price:       625_000,
    bedrooms:    3,
    bathrooms:   2,
    propertyType:'house',
    location:    { address: '7 Richmond Place', city: 'Bath', postcode: 'BA1 5PZ', lat: 51.3944, lng: -2.3536 },
    images:      IMG.houseExterior,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: {},
  },
  {
    title:       'Commercial Studio — Walcot Street',
    description: 'Versatile ground-floor commercial unit on Bath\'s eclectic Walcot Street. Ideal for a gallery, boutique, therapy practice, or studio. Full shopfront, rear access, and a private courtyard.',
    price:       285_000,
    bedrooms:    0,
    bathrooms:   1,
    propertyType:'commercial',
    location:    { address: '52 Walcot Street', city: 'Bath', postcode: 'BA1 5BG', lat: 51.3876, lng: -2.3579 },
    images:      IMG.commercial,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: {},
  },

  // ── OXFORD ────────────────────────────────────────────────────────────────
  {
    title:       '5-Bed Detached — Headington',
    description: 'A handsome detached family home in a premier Headington address. Large reception rooms, a superb kitchen-orangery, a principal suite with en-suite and dressing room, and mature walled gardens of approximately 0.3 acres.',
    price:       1_350_000,
    bedrooms:    5,
    bathrooms:   4,
    propertyType:'house',
    location:    { address: '9 Cuckoo Lane', city: 'Oxford', postcode: 'OX3 8PQ', lat: 51.7602, lng: -1.2068 },
    images:      IMG.luxuryHouse,
    agent:       agentId,
    status:      'active',
    aiDescription: 'An outstanding detached family home positioned in one of Oxford\'s most prestigious residential roads. The generous kitchen-orangery creates a magnificent year-round entertaining space that opens onto beautifully landscaped gardens of approximately a third of an acre. Five bedrooms, four bathrooms, and exceptional presentation throughout.',
    aiValuation: VALUATIONS[2],
  },
  {
    title:       '2-Bed Flat — Jericho',
    description: 'Stylish apartment in Oxford\'s bohemian Jericho quarter. Victorian conversion with high ceilings, a private courtyard garden, and excellent transport links. Walking distance to Oxford city centre and the University.',
    price:       475_000,
    bedrooms:    2,
    bathrooms:   1,
    propertyType:'flat',
    location:    { address: '19 Walton Street', city: 'Oxford', postcode: 'OX2 6AA', lat: 51.7582, lng: -1.2681 },
    images:      IMG.modernFlat,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: VALUATIONS[3],
  },
  {
    title:       '3-Bed Terraced House — Cowley',
    description: 'Well-presented mid-terrace in the popular Cowley area. Two reception rooms, a new kitchen, a low-maintenance rear garden, and off-street parking. Close to the Westgate shopping centre and Oxford Brookes.',
    price:       415_000,
    bedrooms:    3,
    bathrooms:   1,
    propertyType:'house',
    location:    { address: '42 Between Towns Road', city: 'Oxford', postcode: 'OX4 3LX', lat: 51.7402, lng: -1.2219 },
    images:      IMG.houseExterior,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: {},
  },
  {
    title:       'Studio — East Oxford',
    description: 'Compact studio apartment above a boutique retail unit in vibrant East Oxford. Ideal student let or starter home. Exposed brick walls, a fitted kitchenette, and a modern shower room. Bills included lease available.',
    price:       195_000,
    bedrooms:    0,
    bathrooms:   1,
    propertyType:'studio',
    location:    { address: 'Flat A, 88 Cowley Road', city: 'Oxford', postcode: 'OX4 1JB', lat: 51.7481, lng: -1.2345 },
    images:      IMG.studio,
    agent:       agentId,
    status:      'active',
    aiDescription: '',
    aiValuation: {},
  },
];

// ── Seed runner ────────────────────────────────────────────────────────────
async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('Connected to MongoDB\n');

  // Find or create a default agent user
  let agent = await User.findOne({ email: 'agent@meridian.co.uk' });
  if (!agent) {
    agent = await User.create({
      name:     'James Hartley',
      email:    'agent@meridian.co.uk',
      password: 'Meridian2025!',   // plain text — pre-save hook hashes it
      role:     'agent',
    });
    console.log('Created default agent user: agent@meridian.co.uk / Meridian2025!');
  } else {
    console.log(`Using existing agent: ${agent.email}`);
  }

  // Clear existing properties
  const deleted = await Property.deleteMany({});
  console.log(`Cleared ${deleted.deletedCount} existing properties\n`);

  // Insert all 40 mock properties
  const data = mockProperties(agent._id);
  const inserted = await Property.insertMany(data);

  const counts = {
    active:   inserted.filter((p) => p.status === 'active').length,
    sold:     inserted.filter((p) => p.status === 'sold').length,
    archived: inserted.filter((p) => p.status === 'archived').length,
  };

  console.log(`Inserted ${inserted.length} properties:`);
  console.log(`  active:   ${counts.active}`);
  console.log(`  sold:     ${counts.sold}`);
  console.log(`  archived: ${counts.archived}`);

  const cities = [...new Set(inserted.map((p) => p.location.city))].sort();
  console.log(`\nCities covered: ${cities.join(', ')}`);

  await mongoose.disconnect();
  console.log('\nSeed complete.');
}

seed().catch((err) => {
  console.error('Seed failed:', err.message);
  process.exit(1);
});
